name       : eigen3
version    : 3.3.7
release    : 7
homepage   : http://eigen.tuxfamily.org/
source     :
    - https://bitbucket.org/eigen/eigen/get/3.3.7.tar.gz : 7e84ef87a07702b54ab3306e77cea474f56a40afa1c0ab245bb11725d006d0da
license    :
    - BSD-3-Clause
    - BSD-3-Clause-Attribution
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - MPL-2.0
component  : programming
summary    : Eigen is a C++ template library for linear algebra
description: |
    Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms.
patterns   :
    - /usr/include/eigen3
    - /usr/share
setup      : |
    mkdir build && cd build
    %cmake ..
build      : |
    %make -C build
install    : |
    %make_install -C build
