name       : eigen3
version    : 3.3.3
release    : 5
homepage   : http://eigen.tuxfamily.org/
source     :
    - https://bitbucket.org/eigen/eigen/get/3.3.3.tar.gz : 94878cbfa27b0d0fbc64c00d4aafa137f678d5315ae62ba4aecddbd4269ae75f
license    :
    - MPL-2.0
    - BSD-3-Clause
    - GPL-3.0
    - LGPL-2.1
    - BSD-3-Clause-Attribution
summary    : Eigen is a C++ template library for linear algebra.
component  : programming
description: |
    Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms.
patterns   :
    - /usr/include/eigen3
    - /usr/share
setup      : |
    mkdir build && cd build
    %cmake ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
