name       : eigen3
version    : 3.3.5
release    : 6
homepage   : http://eigen.tuxfamily.org/
source     :
    - https://bitbucket.org/eigen/eigen/get/3.3.5.tar.gz : 0454b6bacafd2bf641e0fb0f59572b9995728b77e41d1b8517f807334d07e68e
license    :
    - BSD-3-Clause
    - BSD-3-Clause-Attribution
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - MPL-2.0
component  : programming
summary    : Eigen is a C++ template library for linear algebra
description: |
    Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms.
patterns   :
    - /usr/include/eigen3
    - /usr/share
setup      : |
    mkdir build && cd build
    %cmake ..
build      : |
    %make -C build
install    : |
    %make_install -C build
