name       : eigen3
version    : 3.4.0
release    : 11
homepage   : https://eigen.tuxfamily.org/
source     :
    - https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.bz2 : b4c198460eba6f28d34894e3a5710998818515104d6e74e5cc331ce31e46e626
license    :
    - BSD-3-Clause
    - BSD-3-Clause-Attribution
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - MPL-2.0
component  : programming
summary    : Eigen is a C++ template library for linear algebra
description: |
    Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms.
patterns   :
    - /usr/include/eigen3
    - /usr/share
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
