name        : eigen3
version     : 3.2.7
release     : 1
homepage    : http://eigen.tuxfamily.org/
source      :
    - https://bitbucket.org/eigen/eigen/get/3.2.7.tar.gz : 5a50a006f83480a31f1f9beabec9e91dad95138df19363ee73ccf57676f10405
license     : MPL-2.0
summary     : Eigen is a C++ template library for linear algebra.
description : |
      Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms.
patterns    :
    - [/usr/*]
setup       : |
    mkdir build
    cd build
    %cmake ..
build       : |
    cd build
    %make
install     : |
    cd build
    %make_install